/* Food database + pixel sprites.
   Fiber values are grams of fiber per 100 g of food, rounded from USDA FoodData Central.
   Every food is drawn with one of the shared sprite shapes below, recoloured with its own palette. */
(() => {
  // Letters: o outline · a main · b shade · c highlight · d detail/seeds
  //          g leaf · G dark leaf · s stem · e stalk/extra · w/x/k/l container colours
  const SHAPES = {
    apple: [
      "......oo....",
      "......so.oo.",
      "......sogggo",
      "..oooosooo..",
      ".oaacaaaaao.",
      "oaacaaaaaabo",
      "oacaaaaaaabo",
      "oaaaaaaaaabo",
      "oaaaaaaaabbo",
      ".oaaaaaabbo.",
      "..oaaabbbo..",
      "...oooooo...",
    ],
    round: [
      "......oo....",
      ".....ogGo...",
      "..oooooooo..",
      ".oaaccaaaao.",
      ".oacaaaaaao.",
      "oaacaaaaaabo",
      "oacaaaaaaabo",
      "oaaaaaaaaabo",
      "oaaaaaaaabbo",
      ".oaaaaaabbo.",
      "..oobbbboo..",
      "....oooo....",
    ],
    banana: [
      ".........oo.",
      ".........so.",
      "........oao.",
      "........oao.",
      ".......oaao.",
      "......oaabo.",
      ".....oaaabo.",
      "...ooaaabo..",
      ".ooaaaabbo..",
      "oaaaaabbo...",
      ".obbbbbo....",
      "..ooooo.....",
    ],
    pear: [
      "......o.ooo.",
      "......sogggo",
      ".....oooo...",
      "....oaaco...",
      "....oacao...",
      "...oaaaabo..",
      "..oaacaaabo.",
      ".oaacaaaaabo",
      ".oacaaaaaabo",
      ".oaaaaaaabbo",
      "..oaaaaabbo.",
      "...oooooo...",
    ],
    berry: [
      "....oo.oo...",
      "...ogGoGgo..",
      "..oooooooo..",
      ".ocabcabcao.",
      ".oabbabbabo.",
      "oacabcabcabo",
      "oabbabbabbbo",
      ".ocabcabcao.",
      ".oabbabbabo.",
      "..ocabcabo..",
      "...oabbao...",
      "....oooo....",
    ],
    cluster: [
      "............",
      "............",
      "..ooo..ooo..",
      ".ocaaoocaao.",
      ".oaabooaabo.",
      ".oabbooabbo.",
      "..oooooooo..",
      "...ocaao....",
      "...oaabo....",
      "...oabbo....",
      "....ooo.....",
      "............",
    ],
    strawberry: [
      ".....oo.....",
      "..ooogGooo..",
      ".oagGgGgGao.",
      "oacaggggaabo",
      "oacadaaadabo",
      "oaaaaadaaabo",
      ".oadaaaadbo.",
      ".oaaadaaabo.",
      "..oadaadbo..",
      "...oaaabo...",
      "....oabo....",
      ".....oo.....",
    ],
    avocado: [
      "....oooo....",
      "...oGGGGo...",
      "..oGaaaaGo..",
      "..oGaaaaGo..",
      ".oGaaaaaaGo.",
      ".oGaaddaaGo.",
      "oGaaddddaaGo",
      "oGaadcddaaGo",
      "oGaaddddaaGo",
      ".oGaaddaaGo.",
      "..oGGGGGGo..",
      "...oooooo...",
    ],
    slice: [
      "...oooooo...",
      "..obbbbbbo..",
      ".obaaaaaabo.",
      "obaadaadaabo",
      "obadaccadabo",
      "obaaccccaabo",
      "obaaccccaabo",
      "obadaccadabo",
      "obaadaadaabo",
      ".obaaaaaabo.",
      "..obbbbbbo..",
      "...oooooo...",
    ],
    dried: [
      "............",
      "....oooo....",
      "..ooaacaoo..",
      ".oaacaabaao.",
      ".oabaaaabao.",
      "oaaabaacaabo",
      "oacaabaaabbo",
      ".oaaaabaabo.",
      ".oabaaaabbo.",
      "..oobbbboo..",
      "....oooo....",
      "............",
    ],
    melon: [
      "............",
      "............",
      "oooooooooooo",
      "oaadaaaadaao",
      "ocaaaadaaaco",
      "oGcadaaaacGo",
      ".oGcaaadcGo.",
      "..oGccccGo..",
      "...oGGGGo...",
      "....oooo....",
      "............",
      "............",
    ],
    pineapple: [
      "....o..o....",
      "...ogooGo...",
      "....oGgo....",
      "...oooooo...",
      "..oacbacbo..",
      "..obaabaao..",
      ".oacbacbabo.",
      ".obaabaabbo.",
      ".oacbacbabo.",
      "..obaabaao..",
      "..oacbacbo..",
      "...oooooo...",
    ],
    broccoli: [
      "...oo.ooo...",
      "..ocaocaao..",
      ".ocaabaacao.",
      "oaabaacaabao",
      "oabaacaabaao",
      ".obbaabbaabo",
      "..ooeeeeoo..",
      "....oeeo....",
      "....oeeo....",
      "...oeeeeo...",
      "...oeeeeo...",
      "...oooooo...",
    ],
    carrot: [
      "...o.oo.o...",
      "...ogoGgo...",
      "....oGgo....",
      "..oooooooo..",
      "..oacaaabo..",
      "..oaabaabo..",
      "...ocaabo...",
      "...oaaabo...",
      "....oabbo...",
      "....obao....",
      ".....oao....",
      ".....oo.....",
    ],
    leaf: [
      "........ooo.",
      ".......oaavo",
      "......oaavao",
      ".....oaavabo",
      "....oaavaabo",
      "...oaavaabo.",
      "..oaavabbo..",
      ".oaavabbo...",
      ".oavbbo.....",
      ".ovbo.......",
      ".eoo........",
      "e...........",
    ],
    cabbage: [
      "............",
      "...oooooo...",
      "..oacaaabo..",
      ".oacbaabcao.",
      "oacbaaaabcao",
      "oabaacaaabao",
      "oabacaaaabao",
      "oaabaaaabaao",
      ".oaabbbbaao.",
      "..oaaaaaao..",
      "...oooooo...",
      "............",
    ],
    tuber: [
      "............",
      "............",
      "...oooooo...",
      ".ooaacaaaoo.",
      "oaacaadaaabo",
      "oacaaaaadabo",
      "oaadaaaaaabo",
      ".oaaaadabbo.",
      "..oobbbboo..",
      "....oooo....",
      "............",
      "............",
    ],
    pod: [
      "............",
      "............",
      "...ooooooo.e",
      "..oaaaaaaaoe",
      ".oadcadcadco",
      "oaddaddaddao",
      "obaaaaaaaabo",
      ".obbbbbbbbo.",
      "..oooooooo..",
      "............",
      "............",
      "............",
    ],
    corn: [
      ".....oo.....",
      "....ocao....",
      "...oacaco...",
      "...obabao...",
      "..GoacacoG..",
      "..GobabaoG..",
      ".GgoacacogG.",
      ".GgobabaogG.",
      "oGgoacacogGo",
      "oGggoaaoggGo",
      ".oGggooggGo.",
      "..oooooooo..",
    ],
    tomato: [
      "............",
      ".....oo.....",
      "...oogGoo...",
      "..oaGgGgao..",
      ".oacaGGaaao.",
      "oacaaaaaaabo",
      "oacaaaaaaabo",
      "oaaaaaaaaabo",
      "oaaaaaaaabbo",
      ".oaaaaaabbo.",
      "..oobbbboo..",
      "....oooo....",
    ],
    mushroom: [
      "............",
      "...oooooo...",
      ".ooaacaaaoo.",
      "oaacaaaaaaao",
      "oacaaaaaaabo",
      "obbbbbbbbbbo",
      ".oooeeeeooo.",
      "...oeeeeo...",
      "...oeeeeo...",
      "...oeeeEo...",
      "...oooooo...",
      "............",
    ],
    bulb: [
      ".....g......",
      ".....go.....",
      "....oaco....",
      "...oacaao...",
      "..oacaabao..",
      ".oacaabaabo.",
      ".oaaabaaabo.",
      ".oaaabaabbo.",
      "..oaabaabo..",
      "...oobboo...",
      "....oeeo....",
      "....e.ee....",
    ],
    long: [
      ".........og.",
      "........oggo",
      ".......ogGgo",
      "......oacGo.",
      ".....oacabo.",
      "....oacaabo.",
      "...oacaabo..",
      "..oacaabo...",
      ".oacaabo....",
      ".oaaabo.....",
      ".obbbo......",
      "..ooo.......",
    ],
    bowl: [
      "............",
      "............",
      "...oooooo...",
      ".ooadacadoo.",
      "oadacadadado",
      "oooooooooooo",
      "owkwwwwwwwxo",
      ".owkwwwwwxo.",
      ".owwwwwwwxo.",
      "..owwwwwxo..",
      "...oooooo...",
      "............",
    ],
    bread: [
      "............",
      "..oooooooo..",
      ".oxxxxxxxxo.",
      "oxaaaaaaaaxo",
      "oxacaadaaaxo",
      "oxaaaaaadaxo",
      ".oxadaaaaxo.",
      ".oxaaaadaxo.",
      ".oxaaaaaaxo.",
      ".oxadaaaaxo.",
      ".oxxxxxxxxo.",
      ".oooooooooo.",
    ],
    jar: [
      "..oooooooo..",
      "..ollllllo..",
      "..oooooooo..",
      ".okaaaaaaao.",
      "okaadaadaabo",
      "okwwwwwwwwbo",
      "okwxxxxxxwbo",
      "okwwwwwwwwbo",
      "okadaadaaabo",
      "oaaaadaaaabo",
      ".obbbbbbbbo.",
      "..oooooooo..",
    ],
    packet: [
      ".oooooooooo.",
      ".owwwwwwwwo.",
      ".oxxxxxxxxo.",
      ".owwwwwwwwo.",
      ".owwaddawwo.",
      ".owadadaawo.",
      ".owaddadawo.",
      ".owwaddawwo.",
      ".owwwwwwwwo.",
      ".oxxxxxxxxo.",
      ".oxxxxxxxxo.",
      ".oooooooooo.",
    ],
    nut: [
      "......oo....",
      ".....oaco...",
      "....oacabo..",
      "...oacaabbo.",
      "...oaabaabo.",
      "..oacaababo.",
      "..oaabaabbo.",
      "..oabaabbo..",
      "..oaaabbbo..",
      "...oabbbo...",
      "....oooo....",
      "............",
    ],
    choc: [
      ".oooooooooo.",
      ".ocabcabcao.",
      ".oaabaabaao.",
      ".obbbbbbbbo.",
      ".ocabcabcao.",
      ".oaabaabaao.",
      ".okkkkkkkko.",
      ".oxxxxxxxxo.",
      ".oxwwxxxxxo.",
      ".oxxxxxxxxo.",
      ".oxxxxxxxxo.",
      ".oooooooooo.",
    ],
    tofu: [
      "............",
      "............",
      "..ooooooooo.",
      ".occcccccobo",
      "oooooooooobo",
      "oaaaaaaaaobo",
      "oacaaaaaaobo",
      "oaaaaaaaaobo",
      "oaaaaaaaaobo",
      "oaaaaaaaaoo.",
      "oooooooooo..",
      "............",
    ],
    can: [
      "..oooooooo..",
      ".okkkwwkkko.",
      ".oxxxxxxxxo.",
      ".ocaaggaabo.",
      ".ocagGGgabo.",
      ".ocarrrrabo.",
      ".ocrdrrdrbo.",
      ".ocrrrdrrbo.",
      ".ocardrrabo.",
      ".ocaarraabo.",
      ".oxxxxxxxxo.",
      "..oooooooo..",
    ],
    popcorn: [
      "..oo.ooo.o..",
      ".owwowwwowo.",
      "owwywwowwywo",
      "owywwwwywwwo",
      "oooooooooooo",
      ".orrwwrrwwo.",
      ".orrwwrrwwo.",
      ".orrwwrrwwo.",
      "..orwwrrwo..",
      "..orwwrrwo..",
      "..orwwrrwo..",
      "..oooooooo..",
    ],
  };

  const BASE = { o: "var(--ink)", g: "#6cc24a", G: "#3f8f35", s: "#7a5234", e: "#3f8f35" };
  const SHAPE_PAL = {
    bowl: { w: "#f6f1e3", x: "#d4c9ad", k: "#ffffff" },
    jar: { w: "#fffaf0", x: "#6cc24a", l: "#6cc24a", k: "#ffffff" },
    packet: { w: "#fffaf0", x: "#6cc24a" },
    choc: { k: "#dfe3ea", x: "#3f8f35", w: "#fffaf0" },
    can: { k: "#e8e8f0", w: "#a8a8b8", x: "#c4c4d0" },
    broccoli: { e: "#b8e08a" },
    mushroom: { e: "#f5ead8", E: "#d8c8a8" },
    leaf: { e: "#2a6e2a" },
  };

  // [id, name, fiber per 100 g, shape, palette, portion g, portion label, category, aliases]
  const RAW = [
    // fruit
    ["apple", "apple", 2.4, "apple", { a: "#e8453c", b: "#b52e2e", c: "#ff9b8a" }, 180, "1 medium", "fruit"],
    ["banana", "banana", 2.6, "banana", { a: "#ffd94a", b: "#e0a82e", s: "#6b4a2a" }, 118, "1 medium", "fruit"],
    ["pear", "pear", 3.1, "pear", { a: "#b8d94a", b: "#86a832", c: "#e6f59a" }, 178, "1 medium", "fruit"],
    ["orange", "orange", 2.4, "round", { a: "#ff9a2e", b: "#e0701e", c: "#ffd08a" }, 140, "1 medium", "fruit", ["clementine", "mandarin"]],
    ["peach", "peach", 1.5, "round", { a: "#ffb07a", b: "#f07a5a", c: "#ffe0c0" }, 150, "1 medium", "fruit", ["nectarine"]],
    ["mango", "mango", 1.6, "round", { a: "#ffc03a", b: "#f07a3a", c: "#ffe68a" }, 165, "1 cup", "fruit"],
    ["pomegranate", "pomegranate seeds", 4.0, "round", { a: "#d0304a", b: "#8e1e36", c: "#ff8a9a" }, 87, "½ cup", "fruit", ["arils"]],
    ["raspberries", "raspberries", 6.5, "berry", { a: "#e84a6a", b: "#b02e4e", c: "#ff9ab0" }, 123, "1 cup", "fruit"],
    ["blackberries", "blackberries", 5.3, "berry", { a: "#5a3a7a", b: "#34204a", c: "#9a7aba" }, 144, "1 cup", "fruit"],
    ["blueberries", "blueberries", 2.4, "cluster", { a: "#5a6ad0", b: "#3a44a0", c: "#9aa8f0" }, 148, "1 cup", "fruit"],
    ["grapes", "grapes", 0.9, "cluster", { a: "#9ad04a", b: "#6aa032", c: "#d8f59a" }, 151, "1 cup", "fruit"],
    ["cherries", "cherries", 2.1, "cluster", { a: "#d0303a", b: "#8e1e2a", c: "#ff8a8a" }, 138, "1 cup", "fruit"],
    ["strawberries", "strawberries", 2.0, "strawberry", { a: "#f04a4a", b: "#c02e3a", c: "#ff9a9a", d: "#ffe07a" }, 152, "1 cup", "fruit"],
    ["avocado", "avocado", 6.7, "avocado", { a: "#d8e87a", d: "#8a5a34", c: "#c08a5a", G: "#3a6a2a" }, 75, "½ avocado", "fruit"],
    ["kiwi", "kiwi", 3.0, "slice", { a: "#8ad04a", b: "#7a5a3a", c: "#f0f5c8", d: "#2a2a1a" }, 75, "1 fruit", "fruit", ["kiwifruit"]],
    ["passionfruit", "passion fruit", 10.4, "slice", { a: "#ffd23a", b: "#6a2e5a", c: "#ffe89a", d: "#2a1a1a" }, 18, "1 fruit", "fruit"],
    ["coconut", "coconut (fresh)", 9.0, "slice", { a: "#fffaf0", b: "#7a5234", c: "#fffaf0", d: "#fffaf0" }, 80, "1 cup shredded", "fruit"],
    ["dates", "dates (medjool)", 6.7, "dried", { a: "#8a4a2a", b: "#5a2e1a", c: "#b0704a" }, 24, "1 date", "fruit"],
    ["prunes", "prunes", 7.1, "dried", { a: "#5a2e4a", b: "#3a1a30", c: "#8a5a7a" }, 40, "4 prunes", "fruit", ["dried plums"]],
    ["figs", "dried figs", 9.8, "dried", { a: "#a07a4a", b: "#6a4a2a", c: "#d0a870" }, 40, "5 figs", "fruit"],
    ["raisins", "raisins", 3.7, "dried", { a: "#6a3a4a", b: "#40202e", c: "#9a6070" }, 40, "¼ cup", "fruit", ["sultanas"]],
    ["apricots", "dried apricots", 7.3, "dried", { a: "#ffa03a", b: "#d0701e", c: "#ffd08a" }, 35, "10 halves", "fruit"],
    ["watermelon", "watermelon", 0.4, "melon", { a: "#ff5a6a", d: "#2a1a1a", c: "#f5ffe0" }, 150, "1 cup", "fruit"],
    ["pineapple", "pineapple", 1.4, "pineapple", { a: "#ffd23a", b: "#d09a1e", c: "#fff09a" }, 165, "1 cup", "fruit"],

    // vegetables
    ["broccoli", "broccoli (cooked)", 3.3, "broccoli", { a: "#5fbf4a", b: "#3d8a35", c: "#9ae07a" }, 156, "1 cup", "veg"],
    ["cauliflower", "cauliflower (cooked)", 2.3, "broccoli", { a: "#fff3d0", b: "#e0cf98", c: "#fffaf0", e: "#9ad07a" }, 124, "1 cup", "veg"],
    ["carrot", "carrot", 2.8, "carrot", { a: "#ff8a2e", b: "#e0601e", c: "#ffc08a" }, 61, "1 medium", "veg"],
    ["spinach", "spinach", 2.2, "leaf", { a: "#3d9a3a", b: "#2a6e2a", v: "#7ad06a" }, 30, "1 cup", "veg"],
    ["kale", "kale", 4.1, "leaf", { a: "#2e7a4a", b: "#1e5a36", v: "#6ab07a" }, 21, "1 cup", "veg"],
    ["lettuce", "romaine lettuce", 2.1, "leaf", { a: "#8ad86a", b: "#5fb04a", v: "#d0f5b0", e: "#5fb04a" }, 47, "1 cup", "veg", ["salad", "greens"]],
    ["asparagus", "asparagus", 2.1, "long", { a: "#7ab04a", b: "#4a8a2e", c: "#b8e08a", g: "#8a6aa0", G: "#6a4a80" }, 90, "6 spears", "veg"],
    ["cabbage", "cabbage", 2.5, "cabbage", { a: "#a8e08a", b: "#6ab04a", c: "#e0f8c8" }, 89, "1 cup shredded", "veg", ["coleslaw", "sauerkraut"]],
    ["brussels", "brussels sprouts (cooked)", 2.6, "cabbage", { a: "#6ab04a", b: "#3d8a35", c: "#a8e08a" }, 156, "1 cup", "veg"],
    ["artichoke", "artichoke (cooked)", 8.6, "cabbage", { a: "#7aa86a", b: "#4a7a3a", c: "#b8d8a0" }, 120, "1 medium", "veg"],
    ["sweetpotato", "sweet potato (baked)", 3.3, "tuber", { a: "#d0603a", b: "#a0402a", c: "#f09070", d: "#7a2e1e" }, 150, "1 medium", "veg", ["yam", "kumara"]],
    ["potato", "potato (baked, skin on)", 2.2, "tuber", { a: "#d8b070", b: "#a8804a", c: "#f0d8a0", d: "#7a5a34" }, 173, "1 medium", "veg"],
    ["peas", "green peas (cooked)", 5.5, "pod", { a: "#6ac04a", b: "#3d8a35", d: "#8ae05a", c: "#d0f8a0" }, 160, "1 cup", "veg"],
    ["edamame", "edamame", 5.2, "pod", { a: "#7ab83a", b: "#4a8a2e", d: "#a8d85a", c: "#e0f5b0" }, 155, "1 cup", "veg", ["soybeans"]],
    ["greenbeans", "green beans", 2.7, "pod", { a: "#5fb04a", b: "#3d8a35", d: "#5fb04a", c: "#8ad06a" }, 100, "1 cup", "veg", ["string beans"]],
    ["corn", "sweet corn", 2.4, "corn", { a: "#ffd83a", b: "#e8b02a", c: "#fff09a", g: "#8ad06a", G: "#5fa040" }, 90, "1 ear", "veg"],
    ["tomato", "tomato", 1.2, "tomato", { a: "#f0403a", b: "#b82a2a", c: "#ff9a8a" }, 123, "1 medium", "veg"],
    ["bellpepper", "bell pepper", 2.1, "tomato", { a: "#ff7a2e", b: "#d0501e", c: "#ffc08a" }, 119, "1 medium", "veg", ["capsicum"]],
    ["mushrooms", "mushrooms", 1.0, "mushroom", { a: "#b08a6a", b: "#7a5a44", c: "#d8b898" }, 70, "1 cup", "veg"],
    ["onion", "onion", 1.7, "bulb", { a: "#e8c07a", b: "#b88a4a", c: "#f8e0b0", g: "#b88a4a", e: "#d8c8a8" }, 110, "1 medium", "veg"],
    ["beetroot", "beetroot", 2.8, "bulb", { a: "#a02a5a", b: "#6a1a3e", c: "#d06a90", e: "#a02a5a" }, 82, "1 beet", "veg", ["beets"]],
    ["cucumber", "cucumber", 0.5, "long", { a: "#5fb04a", b: "#3d8a35", c: "#a8e08a", g: "#3d8a35", G: "#2a6a2a" }, 119, "1 cup", "veg"],
    ["zucchini", "zucchini", 1.0, "long", { a: "#3d8a35", b: "#2a6a2a", c: "#8ac86a", g: "#8a7a3a", G: "#6a5a2a" }, 124, "1 cup", "veg", ["courgette"]],
    ["eggplant", "eggplant (cooked)", 2.5, "long", { a: "#7a3a9a", b: "#52206e", c: "#b07ad0" }, 99, "1 cup", "veg", ["aubergine"]],

    // legumes
    ["blackbeans", "black beans (cooked)", 8.7, "bowl", { a: "#3a3040", d: "#1e1a26", c: "#6a6070", chart: "#7a6a9a" }, 172, "1 cup", "legume"],
    ["kidneybeans", "kidney beans (cooked)", 6.4, "bowl", { a: "#a0303a", d: "#6a1a24", c: "#d06a70" }, 177, "1 cup", "legume"],
    ["chickpeas", "chickpeas (cooked)", 7.6, "bowl", { a: "#e8c07a", d: "#c8984a", c: "#f8e0a8" }, 164, "1 cup", "legume", ["garbanzo beans"]],
    ["lentils", "lentils (cooked)", 7.9, "bowl", { a: "#c8703a", d: "#a0502a", c: "#e8a070" }, 198, "1 cup", "legume", ["dal", "dhal"]],
    ["pinto", "pinto beans (cooked)", 9.0, "bowl", { a: "#c8a080", d: "#8a5a44", c: "#e8c8a8" }, 171, "1 cup", "legume", ["refried beans"]],
    ["splitpeas", "split peas (cooked)", 8.3, "bowl", { a: "#b8d05a", d: "#8aa83a", c: "#e0f09a" }, 196, "1 cup", "legume"],
    ["bakedbeans", "baked beans", 4.1, "bowl", { a: "#e8703a", d: "#c04a2a", c: "#ffa070" }, 127, "½ cup", "legume"],
    ["hummus", "hummus", 6.0, "bowl", { a: "#e8c890", d: "#c89a5a", c: "#f8e8c0" }, 30, "2 tbsp", "legume"],
    ["tofu", "tofu (firm)", 2.3, "tofu", { a: "#f5ecd0", c: "#fffaf0", b: "#d8cca8" }, 126, "½ cup", "legume"],

    // grains
    ["oats", "rolled oats (dry)", 10.1, "jar", { a: "#e8d4a0", d: "#c8a870", b: "#c8b080" }, 40, "½ cup", "grain", ["porridge oats", "oatmeal"]],
    ["oatmeal", "oatmeal (cooked)", 1.7, "bowl", { a: "#e8d0a0", d: "#c8a870", c: "#fff0d0" }, 234, "1 cup", "grain", ["porridge"]],
    ["brownrice", "brown rice (cooked)", 1.8, "bowl", { a: "#d8b888", d: "#b8905a", c: "#f0e0c0" }, 195, "1 cup", "grain"],
    ["whiterice", "white rice (cooked)", 0.4, "bowl", { a: "#fffaf0", d: "#e0d8c8", c: "#ffffff" }, 158, "1 cup", "grain"],
    ["quinoa", "quinoa (cooked)", 2.8, "bowl", { a: "#f0e0b0", d: "#c8a86a", c: "#fff8e0" }, 185, "1 cup", "grain"],
    ["barley", "barley (cooked)", 3.8, "bowl", { a: "#e8d8a8", d: "#c0a468", c: "#fff5d8" }, 157, "1 cup", "grain"],
    ["buckwheat", "buckwheat (cooked)", 2.7, "bowl", { a: "#b08a5a", d: "#7a5a34", c: "#d8b888" }, 168, "1 cup", "grain", ["kasha"]],
    ["pasta", "pasta (cooked)", 1.8, "bowl", { a: "#f3d27a", d: "#e0b24e", c: "#fff0b8" }, 140, "1 cup", "grain", ["spaghetti", "noodles"]],
    ["wwpasta", "whole wheat pasta (cooked)", 4.5, "bowl", { a: "#c8984a", d: "#a07030", c: "#e8c080" }, 140, "1 cup", "grain", ["wholemeal pasta"]],
    ["wwbread", "whole wheat bread", 6.0, "bread", { a: "#d8a86a", x: "#8a5a2e", d: "#a0703a", c: "#f0d0a0" }, 32, "1 slice", "grain", ["wholemeal bread", "wholegrain bread"]],
    ["whitebread", "white bread", 2.4, "bread", { a: "#fff3d8", x: "#d8a060", d: "#fff3d8", c: "#fffaf0" }, 25, "1 slice", "grain", ["toast"]],
    ["ryebread", "rye bread", 5.8, "bread", { a: "#a07048", x: "#5a3a20", d: "#7a5030", c: "#c09068" }, 32, "1 slice", "grain", ["pumpernickel"]],
    ["branflakes", "bran flakes", 18.0, "bowl", { a: "#c8844a", d: "#a0602e", c: "#e8b07a" }, 36, "1 cup", "grain", ["cereal"]],
    ["wheatbran", "wheat bran", 42.8, "jar", { a: "#c89a5a", d: "#a0703a", b: "#a07a48", l: "#e0a040" }, 15, "¼ cup", "grain"],
    ["popcorn", "popcorn (air-popped)", 14.5, "popcorn", { w: "#fff8e0", y: "#f5c84a", r: "#e84a4a" }, 24, "3 cups", "grain"],

    // nuts & seeds
    ["chia", "chia seeds", 34.4, "packet", { a: "#b0a8a0", d: "#3a3440", x: "#6cc24a" }, 12, "1 tbsp", "seed"],
    ["flax", "flaxseed (ground)", 27.3, "packet", { a: "#c8904a", d: "#8a5a2e", x: "#e0a040" }, 7, "1 tbsp", "seed", ["linseed"]],
    ["sunflower", "sunflower seeds", 8.6, "packet", { a: "#3a3a3a", d: "#f0e8d8", x: "#ffd23a" }, 35, "¼ cup", "seed"],
    ["pumpkinseeds", "pumpkin seeds", 6.0, "packet", { a: "#6aa04a", d: "#3d7a35", x: "#f08a3a" }, 32, "¼ cup", "seed", ["pepitas"]],
    ["sesame", "sesame seeds", 11.8, "packet", { a: "#f5ead0", d: "#c8b890", x: "#e8453c" }, 9, "1 tbsp", "seed", ["tahini"]],
    ["hemp", "hemp hearts", 4.0, "packet", { a: "#8aa860", d: "#5a7a3a", x: "#3f8f35" }, 30, "3 tbsp", "seed", ["hemp seeds"]],
    ["psyllium", "psyllium husk", 80.0, "jar", { a: "#f0e8d8", d: "#d8ccb0", b: "#d0c4a8", l: "#9ad0e0" }, 5, "1 tsp", "seed", ["metamucil", "isabgol"]],
    ["almonds", "almonds", 12.5, "nut", { a: "#c8844a", b: "#8a5a2e", c: "#e8b07a" }, 28, "1 oz / 23 nuts", "seed"],
    ["pistachios", "pistachios", 10.6, "nut", { a: "#e8d4a8", b: "#b89a6a", c: "#a8d06a" }, 28, "1 oz / 49 nuts", "seed"],
    ["cashews", "cashews", 3.3, "nut", { a: "#f0dca8", b: "#c8a870", c: "#fff5d8" }, 28, "1 oz / 18 nuts", "seed"],
    ["hazelnuts", "hazelnuts", 9.7, "nut", { a: "#a86a3a", b: "#6a4020", c: "#d09a6a" }, 28, "1 oz / 21 nuts", "seed"],
    ["walnuts", "walnuts", 6.7, "nut", { a: "#c89a5a", b: "#8a6030", c: "#e8c088" }, 28, "1 oz / 14 halves", "seed"],
    ["peanuts", "peanuts", 8.5, "nut", { a: "#d8b07a", b: "#a8804a", c: "#f0d8a8" }, 28, "1 oz", "seed"],
    ["peanutbutter", "peanut butter", 5.0, "jar", { a: "#c8843a", d: "#a0602a", b: "#a06a30", l: "#e0503a" }, 32, "2 tbsp", "seed"],

    // other
    ["darkchoc", "dark chocolate (70–85%)", 10.9, "choc", { a: "#6a3e2a", b: "#4a2a1a", c: "#8a5a44", chart: "#9a5e3e" }, 28, "1 oz", "other"],
  ];

  const FOODS = RAW.map(([id, name, per100, shape, pal, portion, portionLabel, cat, aliases]) => ({
    id, name, per100, shape, pal, portion, portionLabel, cat, aliases: aliases || [],
  }));

  // Palette for foods people add themselves
  const CUSTOM_LOOK = { shape: "bowl", pal: { a: "#9ad06a", d: "#6aa040", c: "#d0f0b0" } };

  // Custom sprites for foods people add themselves, matched by name.
  // Only the picture changes; the fiber numbers stay whatever they entered.
  const NAMED_LOOKS = [
    { match: /wild\s*wonder/i, shape: "can", pal: { a: "#ff9ec4", b: "#e46a9e", c: "#ffd4e6", r: "#e8303a", d: "#ffe07a", chart: "#f27aac" } },
  ];
  const BUILTIN_IDS = new Set(RAW.map((r) => r[0]));
  const resolveLook = (food) =>
    (!BUILTIN_IDS.has(food.id) && NAMED_LOOKS.find((l) => l.match.test(food.name || ""))) || food;

  function pixelSvg(rows, fill) {
    let rects = "";
    rows.forEach((row, y) => {
      [...row].forEach((ch, x) => {
        if (fill[ch]) rects += `<rect x="${x}" y="${y}" width="1.02" height="1.02" fill="${fill[ch]}"/>`;
      });
    });
    return `<svg viewBox="0 0 ${rows[0].length} ${rows.length}" shape-rendering="crispEdges" aria-hidden="true">${rects}</svg>`;
  }

  const cache = new Map();
  function foodSvg(food) {
    food = resolveLook(food);
    const shape = food.shape || CUSTOM_LOOK.shape;
    const pal = food.pal || CUSTOM_LOOK.pal;
    const key = shape + JSON.stringify(pal);
    if (!cache.has(key)) cache.set(key, pixelSvg(SHAPES[shape], { ...BASE, ...(SHAPE_PAL[shape] || {}), ...pal }));
    return cache.get(key);
  }

  // Main colour of a food, used for chart segments (`chart` overrides colours too dark to read)
  const foodColor = (food) => { const p = resolveLook(food).pal || CUSTOM_LOOK.pal; return p.chart || p.a || "#6cc24a"; };

  window.FIBER = { FOODS, SHAPES, CUSTOM_LOOK, pixelSvg, foodSvg, foodColor };
})();
