// Prompt pools. Each depth has its own "Write about" topics;
// forms and details are shared, with a few extras for deeper levels.
window.PROMPTS = {
  topics: {
    light: [
      "the best thing you ate this week",
      "a small win from today",
      "your ideal slow Sunday",
      "a song that's been stuck in your head",
      "something that made you laugh recently",
      "the view from your favourite window",
      "a hobby you'd love to try",
      "your comfort movie and why",
      "the last time you felt cosy",
      "a place you'd teleport to right now",
      "an object on your desk",
      "your morning routine",
      "a compliment you received",
      "what's blooming outside right now",
      "a friend who always makes you smile",
      "the perfect cup of tea or coffee",
      "a childhood snack you miss",
      "three things you're grateful for today",
      "a book you'd recommend to everyone",
      "the weather today and how it feels",
      "a tiny luxury you love",
      "your dream bedroom",
      "a smell that makes you happy",
      "something you learned this week",
    ],
    reflective: [
      "a habit you want to build",
      "a lesson a friend taught you",
      "a place that feels like home",
      "a decision you're proud of",
      "the last time you changed your mind",
      "what rest really looks like for you",
      "a boundary you want to set",
      "who you were five years ago",
      "a goal that quietly matters to you",
      "something you've outgrown",
      "a risk worth taking",
      "the kind of friend you want to be",
      "how you spend your first free hour",
      "a tradition you want to keep",
      "what you'd do with a spare year",
      "a mistake that taught you something",
      "a skill you're slowly getting better at",
      "what 'enough' means to you",
      "a relationship that shaped you",
      "the season of life you're in",
      "a question you keep coming back to",
      "a moment you felt truly seen",
      "what drains you and what refills you",
      "someone you'd like to thank",
    ],
    deep: [
      "a fear you've never said out loud",
      "a version of yourself you've grieved",
      "what you'd forgive yourself for",
      "a belief you inherited but never chose",
      "the loneliest you've ever felt",
      "what you're pretending not to know",
      "a moment that split your life in two",
      "the love you give but rarely receive",
      "an apology you're still waiting for",
      "what your anger is trying to protect",
      "a promise you broke to yourself",
      "the part of you that needs the most care",
      "a door you closed on purpose",
      "what you'd say to someone you've lost",
      "the story you tell about your childhood",
      "what success would cost you",
      "a truth that took years to accept",
      "the person you are when no one is watching",
      "an ending you haven't made peace with",
      "what you want but feel you don't deserve",
      "a pattern you keep repeating",
      "the moment you felt most like yourself",
    ],
  },
  forms: {
    light: [
      "a list of 10 things",
      "a postcard to a friend",
      "a haiku",
      "a quick sketch and caption",
      "a restaurant review",
      "a weather report",
      "a tweet-length thought",
      "a to-do list from your future self",
      "a recipe",
      "a mini diary entry",
      "a playlist with liner notes",
      "an advert",
    ],
    reflective: [
      "a letter to your future self",
      "a conversation with a stranger",
      "a letter to your younger self",
      "a list of questions",
      "a map with landmarks",
      "a before-and-after",
      "a gratitude letter you'll never send",
      "three short scenes",
      "a pros and cons table",
      "an interview with yourself",
      "a timeline",
      "a stream of consciousness",
    ],
    deep: [
      "an unsendable letter",
      "a conversation with your inner critic",
      "a eulogy for an old habit",
      "a stream of consciousness",
      "a letter from your body",
      "a dialogue between past and present you",
      "a confession",
      "a fairytale where you're the hero",
      "a letter to someone you've lost",
      "the third person, like a novel",
      "a manifesto",
      "a dream journal entry",
    ],
  },
  details: {
    light: [
      "a colour you can see right now",
      "a sound from your surroundings",
      "a favourite snack",
      "something soft",
      "the time of day",
      "an animal",
      "a word you love",
      "an exclamation mark!",
      "a small plant or flower",
      "a smell",
    ],
    reflective: [
      "a specific date",
      "a scent memory",
      "a piece of advice",
      "a physical sensation",
      "the word 'maybe'",
      "a question you can't answer",
      "one sentence in the present tense",
      "a quote you remember",
      "a place name",
      "a turning point",
    ],
    deep: [
      "one sentence that starts with 'I wish'",
      "what your body felt at the time",
      "a colour for the feeling",
      "the words you never said",
      "one thing you're letting go of",
      "a detail no one else knows",
      "an object that holds the memory",
      "a single line of self-compassion",
      "the phrase 'and still'",
      "what you need now",
    ],
  },
  quotes: [
    ["Fill your paper with the breathings of your heart.", "William Wordsworth"],
    ["Writing is the painting of the voice.", "Voltaire"],
    ["Know thyself.", "Delphic maxim"],
    ["The soul becomes dyed with the colour of its thoughts.", "Marcus Aurelius"],
    ["Be gentle with yourself; you are doing your best.", "Journalcize"],
    ["A page a day keeps the fog away.", "Journalcize"],
    ["Write it messy. Tidy is for later.", "Journalcize"],
    ["Hope is the thing with feathers.", "Emily Dickinson"],
    ["The unexamined life is not worth living.", "Socrates"],
    ["Nothing is ever really lost to us as long as we remember it.", "L. M. Montgomery"],
    ["Every day may not be good, but there's something good in every day.", "Proverb"],
    ["Small steps, soft heart, steady pen.", "Journalcize"],
    ["What we think, we become.", "Buddhist proverb"],
    ["Stars can't shine without darkness.", "Proverb"],
  ],
};
